### ISSUE TITLE
评价填写部分

### ISSUE THREAD

**Issue by huangjinze** [IcyCC/bjfu_supervision_back#102]
PS：
1、在取课程列表时：过滤掉“补考”、“缓考”等课程。
2、课程检索列表需要包括本学期和上学期的课程。

bug：
点击课程名称，选择课程报错：系统异常。

request header
`GET /api/lessons?term=%222017-2018-1%22&lesson_name_like=%22250%22 HTTP/1.1
Host: 202.204.121.155:10080
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36
Referer: http://202.204.121.155:10080/?
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9
Cookie: remember_web_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6Ik5ZQWlmcEdDb2dMM2cxMVYyRlByN1E9PSIsInZhbHVlIjoiN0RqcVNNMGExMFV4bVpFVmVSbnU3RGRUS1FJVlhVb1JLd3hWek5KVFZQQ25uV1NnUVV3cFNMRzVyRWhwTWR4aEVyUXlKRk5LQTdYY0owaDJCZDh3MWVxWGhTRkZDXC9DOEd6OGNiVjRrNVMwPSIsIm1hYyI6IjJjZTExYzMxNjVkODY3ZWE5NDIxMWMyNTZiYjNkN2VjYWQwZTIwYzdhODcyNDY1NzkyZGNkYmI4OWVkZDhiYWYifQ%3D%3D; session=.eJwlzjEOwzAIQNG7MGcA2-CQy0TGgNo1aaaqd6_abH950n_DnkecD9hexxUL7E-HDdSyCXsVQ5nq4jQKu2OmtqFMXNEr00BNMnLELhFae5tTJ5eohpw9WivepveS6_hpseFSw7OyGuZqzYcRu3WxQlgk_j0nLHCdcdwzBJ8vym0wGw.XMV3XA.QEZ4Bmz55rBk3lcDVe3mkhnrzv8
`

response
`{
  "code": 500, 
  "msg": "unsupported operand type(s) for +: 'int' and 'str'"
}
`

**Comment by IcyCC** [comment]
这个应该已经修了

**Comment by huangjinze** [comment]
我晚上刚测的，是不是没拉代码




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: suchang <notifications@github.com>
发送时间: 2019年4月29日 22:36
收件人: IcyCC/bjfu_supervision_back <bjfu_supervision_back@noreply.github.com>
抄送: CCB <395547903@qq.com>, Author <author@noreply.github.com>
主题: 回复：[IcyCC/bjfu_supervision_back] 评价填写部分 (#102)




这个应该已经修了

**Comment by IcyCC** [comment]
我看下

**Comment by IcyCC** [comment]
@Victordong  
![image](https://user-images.githubusercontent.com/8396083/56907303-86e1c780-6ad6-11e9-9991-faa6b440131d.png)

lesson_case 返回的值不对 { lesson_case: [{case1}, {case2}]}, 不是 {lesson_case: [[{case1}, {case2}], total]} 看下这次接口返回值错误的原因

**Comment by IcyCC** [comment]
@Victordong  
![image](https://user-images.githubusercontent.com/8396083/56907303-86e1c780-6ad6-11e9-9991-faa6b440131d.png)

lesson_case 返回的值不对 { lesson_case: [{case1}, {case2}]}, 不是 {lesson_case: [[{case1}, {case2}], total]} 看下这次接口返回值错误的原因

**Comment by IcyCC** [comment]
fix

**Comment by IcyCC** [comment]
测了提交的流程
