### ISSUE TITLE
评价体系管理

### ISSUE THREAD

**Issue by huangjinze** [IcyCC/bjfu_supervision_back#103]
1、编辑现有评价体系时报错：
`{
  "code": 500, 
  "msg": "E11000 duplicate key error collection: supervision.form_meta index: _id_ dup key: { : \"5cc70abc9dc6d6fd47598cb2\" }"
}
`
2、方便的话增加一个删除评价体系的按钮。

**Comment by IcyCC** [comment]
加个删除 把更新功能下了吧

**Comment by huangjinze** [comment]
1.第一次更新没有问题，第二次再点击更新的时候报错了

{
  "code": 500, 
  "msg": "E11000 duplicate key error collection: supervision.form_meta index: _id_ dup key: { : \"5cc993359dc6d619275d31f0\" }"
}
2.每次你们操作完表之后，我第一次创建总会建出一张没有名字的评价体系来，错误没追到，创建完提示创建成功，然后就跳转页面了

**Comment by IcyCC** [comment]
这个我把更新功能下了, 因为这个之前的版本是更新时候会创建一个新版本的问卷, 现在只能创建新的问卷 没有版本这个概念了

**Comment by IcyCC** [comment]
如果直接更新之前已经提交了的不太好处理

**Comment by IcyCC** [comment]
我试一下

**Comment by huangjinze** [comment]
感觉应该没啥问题了这一块，这样吧，你明天告诉我nosq内部关键字段的l存储格式，我把第一版和第二版的问卷内容按照格式整理好你导进去，总共应该有9种不同的评价内容吧（一个一个输太慢了，错了就得重头来，你直接操作数据库方便些。）
