### ISSUE TITLE
评价体系管理中选择课程部分

### ISSUE THREAD

**Issue by huangjinze** [IcyCC/bjfu_supervision_back#107]
光列出课程名是不行的，无法知道第几节课那个班级上的。
![image](https://user-images.githubusercontent.com/8840253/57017804-52dfe100-6c53-11e9-8ea4-62b41200c2ad.png)
要把详细信息列出来

**Comment by huangjinze** [comment]
把这几个框开放成让让他们可以自行修改的吧，不做禁止修改的要求了
![image](https://user-images.githubusercontent.com/8840253/57017851-90446e80-6c53-11e9-9448-d242b084e493.png)

**Comment by IcyCC** [comment]
fix

**Comment by huangjinze** [comment]
补考缓考的课程没有过滤掉，感觉课不全，是没有全部导进去嘛

**Comment by huangjinze** [comment]
这个地方的搜索要麻烦一些：
教师名字及其模糊搜索，课程名称及其模糊搜索

**Comment by IcyCC** [comment]
课程表那个fiix了 然后 那块模糊搜索 就是 先搜教师名 然后空格 搜课程名这样可以不

**Comment by huangjinze** [comment]
这个恐怕不行，老师们对于课程的搜索量还是蛮大的，最好两个都匹配（先搜索教师名或者课程名都能匹配到）


------------------ 原始邮件 ------------------
发件人: suchang <notifications@github.com>
发送时间: 2019年5月4日 11:36
收件人: IcyCC/bjfu_supervision_back <bjfu_supervision_back@noreply.github.com>
抄送: CCB <395547903@qq.com>, Author <author@noreply.github.com>
主题: 回复：[IcyCC/bjfu_supervision_back] 评价体系管理中选择课程部分 (#107)




课程表那个fiix了 然后 那块模糊搜索 就是 先搜教师名 然后空格 搜课程名这样可以不

**Comment by huangjinze** [comment]
我看看以前的sql语句能不能复用，若是可以晚上给你


------------------ 原始邮件 ------------------
发件人: suchang <notifications@github.com>
发送时间: 2019年5月4日 11:36
收件人: IcyCC/bjfu_supervision_back <bjfu_supervision_back@noreply.github.com>
抄送: CCB <395547903@qq.com>, Author <author@noreply.github.com>
主题: 回复：[IcyCC/bjfu_supervision_back] 评价体系管理中选择课程部分 (#107)




课程表那个fiix了 然后 那块模糊搜索 就是 先搜教师名 然后空格 搜课程名这样可以不

**Comment by huangjinze** [comment]
不行，刚刚看了看，这一块在老版里是if else硬写的，没啥帮助




------------------ 原始邮件 ------------------
发件人: "suchang"<notifications@github.com>;
发送时间: 2019年5月4日(星期六) 中午11:36
收件人: "IcyCC/bjfu_supervision_back"<bjfu_supervision_back@noreply.github.com>;
抄送: "黄金泽"<395547903@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [IcyCC/bjfu_supervision_back] 评价体系管理中选择课程部分 (#107)




课程表那个fiix了 然后 那块模糊搜索 就是 先搜教师名 然后空格 搜课程名这样可以不

**Comment by IcyCC** [comment]
懂了

**Comment by IcyCC** [comment]
修了 现在搜 名字 和 教师名字都行了

**Comment by huangjinze** [comment]
搜索课程名字或者教师（你是不是把数据库更新了所以没有返回数据）
{
  "code": 200, 
  "lessons": [], 
  "msg": "", 
  "total": 0
}
