### ISSUE TITLE
督导端课程表跳转评价表问题

### ISSUE THREAD

**Issue by huangjinze** [IcyCC/bjfu_supervision_back#120]
![image](https://user-images.githubusercontent.com/8840253/57457025-51409980-72a1-11e9-9e1e-bb150767b994.png)
点击评价后，跳转评价首页
{
  "code": 200, 
  "total": 0, 
  "work_plans": []
}

**Comment by IcyCC** [comment]
修了

**Comment by IcyCC** [comment]
用 2017-2018-2 学期
